# Generated by Django 4.2.1 on 2023-06-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0003_alter_artefact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year_monument',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
