# Generated by Django 4.2.1 on 2023-06-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0004_alter_year_monument_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
